### ISSUE TITLE
No longer displaying for Spotify Connect

### ISSUE THREAD

**Issue by jdowning** [serban/menubar-ticker#2]
👋 Hello! Thanks for creating this application! Today, I noticed it was no longer displaying the song details in the menu bar when using Spotify. I wonder if this has something to do with an update in Spotify's app recently? Also, the menu bar icon is not 🎵 but rather a dash `-`. 

macOS 10.14.5
Spotify 1.1.9.383.g9f48828e

Let me know if you need any further information to help figure this out. Thanks!

**Comment by jdowning** [comment]
Hmm, this seems like it was my issue with using a Spotify Connect device. Resetting the output device back to my computer resolved this.

**Comment by jdowning** [comment]
Hi @serban ...after another look, this does seem like a bug. If I use Spotify Connect to listen on an external device, Menu Bar Ticker no displays the currently playing track (as described earlier in this issue). Any help or advice would be much appreciated. Thanks!

**Comment by serban** [comment]
The Spotify app must be doing something different for Spotify Connect. If you're seeing just a dash in the menu bar then Spotify is providing an empty artist and name, and Menu Bar Ticker doesn't know any better.

Just to confirm: does it still work correctly for regular playback on your Mac?

I'm pleasantly surprised that this little app has worked for seven years without breaking. Let me see what I can do.

**Comment by serban** [comment]
Just verified that Menu Bar Ticker v1.0.0 still works for Spotify 1.1.10.540.gfcf0430f on High Sierra (10.13.6) and Mojave (10.14.5).

Using Spotify Connect between two Macs running Menu Bar Ticker, they both show the correct artist and title when playback is active.

Unfortunately, I cannot see my Chromecast or Google Home devices in the Spotify desktop client, so I cannot test those.

The scripting bridge header for Spotify has not changed significantly since 2012, so the breakage is not due to API incompatibility there.

Updating issue title to reflect problem with Spotify Connect.

**Comment by serban** [comment]
@jdowning Since I cannot reproduce this issue, I don't know how to fix it. I'm inclined to think the problem is not in Menu Bar Ticker. The song metadata is obtained in a single line, and if the data therein is not good, there is not much I can do about it.

https://github.com/serban/menubar-ticker/blob/c64cc131d9077936486616c93aa13bb238c5fced/MenubarTicker/AppDelegate.m#L105

**Comment by serban** [comment]
I was able to reproduce the problem by running the Spotify web player and casting to my Chromecast and Google Home devices. When the Spotify desktop client is also running, Menu Bar Ticker talks to it but receives empty metadata about the artist and track title.

You can verify this without installing Menu Bar Ticker using this bit of AppleScript:

```AppleScript
tell application "Spotify"
	log artist of the current track & " - " & name of the current track
end tell
```

As per my previous comment, this is likely a problem in the Spotify desktop client.

**Comment by serban** [comment]
@jdowning Looks like other people are seeing this issue with Spotify as well.

https://community.spotify.com/t5/Desktop-Mac/Bug-AppleScript-Spotify-Connect-Recent-update-broke-AppleScript/m-p/4778252

**Comment by jdowning** [comment]
@serban Thanks for taking the time on this issue. Sounds like we'll just have to wait for Spotify to hopefully fix the behavior in an update. 👍
