### ISSUE TITLE
Add support for Swinsian?

### ISSUE THREAD

**Issue by bobtheguitar** [serban/menubar-ticker#8]
Thanks so much for the app! Simple, works. This is perhaps a bit niche, but: any chance of adding support for [Swinsian](https://swinsian.com)?

**Comment by serban** [comment]
A cursory look at their website suggests it's possible to support Swinsian using a scripting bridge and notifications, just like for the others players currently supported.

* https://swinsian.com/support/scripting
* https://swinsian.com/support/developers

But since it's a paid app (that I don't currently use), I'm hesitant to add this support myself and then have to maintain it.

Would you like to give it a try? You can look through the commit messages in this repository to see what's involved.

**Comment by bobtheguitar** [comment]
That’s fair! Thanks for the reply. I doubt I’m competent to do it, to be honest, however simple it may be—but will look into it.

On 22 Jan 2021, at 00:43, Serban Giuroiu <notifications@github.com<mailto:notifications@github.com>> wrote:



A cursory look at their website suggests it's possible to support Swinsian using a scripting bridge and notifications, just like for the others players currently supported.

  *   https://swinsian.com/support/scripting
  *   https://swinsian.com/support/developers

But since it's a paid app (that I don't currently use), I'm hesitant to add this support myself and then have to maintain it.

Would you like to give it a try? You can look through the commit messages in this repository to see what's involved.
